apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lgzzl5rjn-go
  janus-idp.io/tekton: lgzzl5rjn-go
  backstage.io/kubernetes-id: lgzzl5rjn-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lgzzl5rjn-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
